#RESOURCE ADAPTERS
RESOURCE_ADAPTERS=JDG

JDG_ID=infinispanRemQSDSL
JDG_MODULE_SLOT=main
JDG_MODULE_ID=org.jboss.teiid.resource-adapter.infinispan.dsl
JDG_CONNECTION_CLASS=org.teiid.resource.adapter.infinispan.dsl.InfinispanManagedConnectionFactory
JDG_CONNECTION_JNDI=java:/infinispanRemoteDSL
JDG_PROPERTY_CacheTypeMap=default:org.jboss.as.quickstarts.datagrid.hotrod.query.domain.Person;id
JDG_PROPERTY_ProtobufDefinitionFile=/home/jboss/source/injected/addressbook.proto
JDG_PROPERTY_MessageDescriptor=quickstart.Person
JDG_PROPERTY_Module=com.client.quickstart.addressbook.pojos
JDG_PROPERTY_MessageMarshallers=org.jboss.as.quickstarts.datagrid.hotrod.query.domain.Person:org.jboss.as.quickstarts.datagrid.hotrod.query.marshallers.PersonMarshaller
JDG_PROPERTY_RemoteServerList=##HOTROD_SERVICE_HOST##:11333
